<a href="https://colab.research.google.com/github/Shavitjnr/NumPy/blob/main/01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Create NumPy Array using NumPy Function**

# Zeros

In [20]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [23]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print(ar_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [26]:
ar_em = np.empty(4)
ar_em1 = np.empty((3,4))
print(ar_em)
print(ar_em1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Range

In [27]:
ar_rn = np.arange(4)
ar_rn1 = np.arange(3,10,2)
print(ar_rn)
print(ar_rn1)

[0 1 2 3]
[3 5 7 9]


# Diagonal

In [28]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace

In [33]:
ar_lin = np.linspace(1,20,num=5)
print(ar_lin)

[ 1.    5.75 10.5  15.25 20.  ]
