<a href="https://colab.research.google.com/github/Shavitjnr/NumPy/blob/main/01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy in Python**
**Introduction**
1. What is NumPy ?
2. What is NumPy Array ?
3. NumPy vs Python List
4. Installation & Import NumPy
5. Importance of NumPy in Python


In [ ]:
import numpy as np
x= np.array ([1,2,3,4])
print(x)

[1 2 3 4]


In [ ]:
import numpy as np
x=[1,2,3,4]
y=(1,2,3,4)
z={1,2,3,4}
print(x,y,z)

[1, 2, 3, 4] (1, 2, 3, 4) {1, 2, 3, 4}


In [ ]:
%timeit [j**4 for j in range(1,9)]

780 ns ± 31.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,9)**4

1.83 µs ± 347 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Array

In [ ]:
import numpy as np
x=[1,2,3,4]
y= np.array([1,2,3,4,5])
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
l = []
for i in range(1,6):
  int_1 = input("Enter your number: ")
  l.append(int_1)

print(np.array(l))

Enter your number: 1
Enter your number: 2
Enter your number: 3
Enter your number: 4
Enter your number: 5
['1' '2' '3' '4' '5']


# Zeros

In [ ]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [ ]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print(ar_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [ ]:
ar_em = np.empty(4)
ar_em1 = np.empty((3,4))
print(ar_em)
print(ar_em1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Range

In [ ]:
ar_rn = np.arange(4)
ar_rn1 = np.arange(3,10,2)
print(ar_rn)
print(ar_rn1)

[0 1 2 3]
[3 5 7 9]


# Diagonal

In [ ]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace

In [ ]:
ar_lin = np.linspace(1,20,num=5)
print(ar_lin)

[ 1.    5.75 10.5  15.25 20.  ]
