<a href="https://colab.research.google.com/github/Shavitjnr/NumPy/blob/main/03_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Creating NumPy Arrays with Random Numbers**

# Random


# Rand()
The function is used to generate a random values between 0 to 1.

In [2]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.87413174 0.02989739 0.94804829 0.18015925]


In [3]:
var1 = np.random.rand(2,5)
print(var1)

[[0.9344887  0.5830211  0.5536286  0.3617098  0.42404881]
 [0.96490593 0.27183404 0.15854118 0.81621269 0.61798212]]


# randn()
The functionn is used to generate a random value close to zero. This may return positive or negative numbers as well.

In [4]:
var2 = np.random.randn(5)
print(var2)

[0.01843217 0.43142295 1.14935027 1.93573447 0.32247274]


# randf()
The functionn for doing random sampling in numpy. It returns an array of specified shape and fills it with randoom floats in the half open interval (0.0,1.0)

In [6]:
var3 = np.random.ranf(5)
print(var3)

[0.19886834 0.14154622 0.15125199 0.3906109  0.58015733]


# randint()
The function is used to generate a random number has a given range.

In [10]:
var4 = np.random.randint(5,20,5)
print(var4)

[11 10  6 16  9]
