<a href="https://colab.research.google.com/github/Shavitjnr/NumPy/blob/main/04_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Types in NumPy Arrays**

In [15]:
import numpy as np
var = np.array([1,2,3,4])
print("Data Type: ",var.dtype)

Data Type:  int64


In [ ]:
import numpy as np
var = np.array([1,2,3,4,12,13,14,15,16])
print("Data Type: ",var.dtype)

In [17]:
var = np.array([1.0,1.2,3.4])
print("Data Type: ",var.dtype)

Data Type:  float64


In [18]:
var = np.array(["A","M","I","T"])
print("Data Type: ",var.dtype)

Data Type:  <U1


In [19]:
var = np.array(["A","M","I","T",1,2,3,4,5,6])
print("Data Type: ",var.dtype)

Data Type:  <U21


In [22]:
X = np.array([1,2,3,4,5],dtype = np.int8)
print("Data Type: ",X.dtype)
print(X)

Data Type:  int8
[1 2 3 4 5]


In [23]:
X1 = np.array([1,2,3,4,5],dtype = "f")
print("Data Type: ",X1.dtype)
print(X1)

Data Type:  float32
[1. 2. 3. 4. 5.]


In [28]:
X2 = np.array([1,2,3,4,5])
new = np.float32(X2)
print("Data Type: ",X2.dtype)
print("Data Type: ",new.dtype)
print(X2)
print(new)

Data Type:  int64
Data Type:  float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [30]:
X2 = np.array([1,2,3,4,5])
new = np.float32(X2)
new1 = np.int_(new)
print("Data Type: ",X2.dtype)
print("Data Type: ",new.dtype)
print("Data Type: ",new1.dtype)
print(X2)
print(new)
print(new1)

Data Type:  int64
Data Type:  float32
Data Type:  int64
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [31]:
x3 = np.array([1,2,3,4,5])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
